spring.application.name=deppgram-audio-convertor
server.port=5602
# application.properties
logging.level.org.springframework=DEBUG
deepgram.api.key=1d27ec7749a69c8e55373bc7d8a7ce55e9947d77
deepgram.api.url=https://api.deepgram.com/v1/listen?diarize=true

