spring.application.name=chatbot-backend
server.port=5600
# application.properties
logging.level.org.springframework=DEBUG
openai.api.key=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
